# Generated by Django 4.1.3 on 2022-12-08 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
