# Generated by Django 4.1.3 on 2022-12-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_director'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='demo_link',
            new_name='vimeo_link',
        ),
    ]
