# Generated by Django 4.1.3 on 2022-12-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_project_renta_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=280)),
                ('mail', models.EmailField(max_length=254)),
                ('titulo', models.CharField(max_length=280)),
                ('contenido', models.TextField(max_length=4000)),
            ],
        ),
    ]
