# Generated by Django 4.1.3 on 2023-01-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0025_alter_project_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disponible_fisico',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
