# Generated by Django 4.1.3 on 2023-01-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_project_disponible_fisico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='disponible_fisico',
            field=models.IntegerField(choices=[(0, 'No Disponible'), (1, 'Disponible')], default=0),
        ),
    ]
