# Generated by Django 4.1.3 on 2022-12-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_demo_link_project_vimeo_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
