# Generated by Django 4.1.3 on 2022-12-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='subtitle',
            field=models.SlugField(blank=True, max_length=280, null=True),
        ),
    ]
