# Generated by Django 4.1.3 on 2022-12-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_entrada_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='subtitle',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
