# Generated by Django 4.1.3 on 2022-12-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_entrada_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='fotografo',
            field=models.TextField(blank=True, max_length=280, null=True),
        ),
    ]
