# Generated by Django 4.1.3 on 2022-12-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_alter_project_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
