# Generated by Django 4.1.3 on 2022-12-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_entrada_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='renta_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
